name: 'Setup Tectonic'
description: 'Sets up Tectonic for Github Actions'
author: 'WtfJoke'
inputs:
  github-token:
    required: true
    description: 'The GITHUB_TOKEN secret. Used for querying tectonic releases'
  tectonic-version: 
    required: false
    description: 'The version of tectonic to install. A value of `latest` will install the latest version of tectonic. Defaults to `latest`.'
    default: 'latest'
  
runs:
  using: 'node12'
  main: 'dist/index.js'
