name: 'Setup Tectonic'
description: 'Sets up Tectonic for Github Actions to compile your LaTeX documents'
author: 'WtfJoke (Manuel)'

inputs:
  github-token:
    required: true
    description: 'The GITHUB_TOKEN secret. Used for querying tectonic releases'
  tectonic-version: 
    required: false
    description: 'The version of tectonic to install. A value of `latest` will install the latest version of tectonic. Defaults to `latest`.'
    default: 'latest'
  biber-version: 
    required: false
    description: 'The version of biber to install. A value of `latest` will install the latest version of biber.'
  
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: gray-dark