name: 'On Release'
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-tag:
    name: 'Update major version tag to latest version'
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{github.event.release.tag_name}}
    steps:
      - uses: actions/checkout@v5
      - name: Update major version tag
        run: |
          major=`echo $TAG_NAME | cut -d. -f1`
          git tag $major
          git push -f origin $major
