name: "CI"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn all
      - name: Verify dist files are up to date
        if: github.actor != 'dependabot[bot]'
        run: |
          # Fail if "yarn run build && yarn run package" generated new changes in dist
          git update-index --refresh dist/* && git diff-index --quiet HEAD dist
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.4.0
          biber-version: 2.15
      - name: Tectonic version
        run: tectonic --version
      - name: Biber version
        run: biber --version
