name: 'CI'
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          yarn install
      - run: |
          yarn all
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.14.1
          biber-version: 2.17
      - name: Tectonic version
        run: tectonic --version
      - name: Biber version
        run: biber --version
